
spring:
  application:
    name: Restaurant-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myDineRestaurant
    username: arnav
    password: mindfire
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8700

# Rabbitmq setup
rabbitmq:
  host: localhost
  port: 8032

